
use_frameworks!

target 'LocationPlugin_Example' do
  pod 'LocationPlugin', :path => '../'

  target 'LocationPlugin_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
